apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw17
  template:
    metadata:
      labels:
        app: hw17
    spec:
      containers:
        - name: library-app
          image: library-app:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/library"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"

        - name: library-db
          image: postgres:14-alpine
          env:
            - name: POSTGRES_DB
              value: "library"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password"

---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  type: NodePort
  selector:
    app: hw17
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: library-db-service
spec:
  type: ClusterIP
  selector:
    app: hw17
  ports:
    - port: 5432
      targetPort: 6541