apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw17
  template:
    metadata:
      labels:
        app: hw17
    spec:
      containers:
        - name: hw17-container
          image: hw17
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hw17
spec:
  type: NodePort
  selector:
    app: hw17
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080