spring:
  h2:
    console:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:mem:maindb;MODE=LEGACY
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    location: classpath:db/migration
  sql:
    init:
      mode: never

  logging:
    level:
      org:
        springframework:
          security:
            acls: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG # Чтобы видеть SQL