logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE


spring:
  r2dbc:
    username: sa
    password: password
    url: r2dbc:h2:mem:///testdb

  flyway:
    url: jdbc:h2:mem:testdb


    enabled: true
    location: classpath:db/migration
  sql:
    init:
      mode: never


