spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: password
  flyway:
    url: jdbc:h2:mem:testdb
    enabled: true
    location: classpath:db/migration
  sql:
    init:
      mode: never

