spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: library
      username: admin
      password: password
mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs

