spring:
  flyway:
    enabled: true
  location: classpath:db/migration
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: never
      data-locations: data.sql
      schema-locations: schema.sql