server:
  port: 8081
feign:
  httpclient:
    hc5:
      enabled: true
resilience4j.ratelimiter:
  instances:
    frontendRateLimitedService:
      limit-for-period: 8
      limit-refresh-period: 1m
      timeout-duration: 0