name: Build

on:
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - uses: actions/checkout@v4
      - name: Cache embedded MongoDB
        uses: actions/cache@v3
        with:
          path: ~/.embedmongo
          key: ${{ runner.os }}-embedmongo-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-embedmongo-

      - name: Build application
        run: |
          mvn verify --no-transfer-progress
